[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "module_deep_learning"
version = "0.0.1"
description = "Deep Learning"
authors = [
  { name = "vitu_lindu" },
]

readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    
]
dependencies = [
    "ipykernel>=7.3.0",
    "ipython",
    "jupyterlab",
    "loguru",
    "matplotlib",
    "mkdocs",
    "notebook",
    "numpy",
    "pandas",
    "pip",
    "pytest",
    "python-dotenv",
    "ruff",
    "scikit-learn",
    "tensorflow>=2.21.0",
    "tqdm",
    "typer",
]
requires-python = "==3.12.6"


[tool.ruff]
line-length = 99
src = ["module_deep_learning"]
include = ["pyproject.toml", "module_deep_learning/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]  # Add import sorting

[tool.ruff.lint.isort]
known-first-party = ["module_deep_learning"]
force-sort-within-sections = true

